# Generated by Django 4.2.3 on 2023-07-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_artwork_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerygroup',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
