# Generated by Django 4.2.3 on 2023-07-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallerygroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gallerygroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
